"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from urllib import parse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # custom apps
    "accounts.apps.AccountsConfig",
    "etl_pipelines.apps.ETLPipelinesConfig",
    # installed apps
    "rest_framework",
    "rest_framework.authtoken",
    'corsheaders',
    "notifications"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

CORS_ORIGIN_ALLOW_ALL = True


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        "OPTIONS": {"user_attributes": ("email", "first_name", "last_name")},
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = "http://127.0.0.1:8000/static/"

STATIC_URL = "http://139.162.203.47:3001/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "accounts.User"


APPEND_SLASH = False


# EFT MDB
# EFT_ENGINE_USER = os.environ.get("EFT_ENGINE_USER")
# EFT_ENGINE_PASS = os.environ.get("EFT_ENGINE_PASS")
# EFT_ENGINE_HOST = os.environ.get("EFT_ENGINE_HOST")
# EFT_ENGINE_PORT = os.environ.get("EFT_ENGINE_PORT")
# EFT_ENGINE = os.environ.get("EFT_ENGINE")
EFT_ENGINE_USER = os.environ.get("EFT_MDB_USER")
EFT_ENGINE_PASS = os.environ.get("EFT_MDB_PASS")
EFT_ENGINE_HOST = os.environ.get("EFT_MDB_HOST")
EFT_ENGINE_PORT = os.environ.get("EFT_MDB_PORT")
EFT_ENGINE = os.environ.get("EFT_MDB_ENGINE")
EFT_ENGINE_CONN_URL = f"mongodb://{EFT_ENGINE_USER}:{parse.quote_plus(EFT_ENGINE_PASS)}@{EFT_ENGINE_HOST}:{EFT_ENGINE_PORT}/{EFT_ENGINE}"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.BearerTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.CustomPagination.CustomPagination',
    'PAGE_SIZE': 20
}

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

